//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.TestTools.UnitTesting {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FailedTestMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal FailedTestMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.TestTools.UnitTesting.FailedTestMessage", typeof(FailedTestMessage).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence contains one or more duplicate elements..
        /// </summary>
        internal static string AllItemsAreNotUnique {
            get {
                return ResourceManager.GetString("AllItemsAreNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PropertyChanged event was not raised for all properties..
        /// </summary>
        internal static string AllPropertiesChangedNotRaised {
            get {
                return ResourceManager.GetString("AllPropertiesChangedNotRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PropertyChanged event was raised for all properties..
        /// </summary>
        internal static string AllPropertiesChangedRaised {
            get {
                return ResourceManager.GetString("AllPropertiesChangedRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected collection change action was {0}, but the actual action is {1}..
        /// </summary>
        internal static string CollectionChangedActionNotExpected {
            get {
                return ResourceManager.GetString("CollectionChangedActionNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotifyCollectionChangedEventArgs.{0} property was expected to have a count of {1}..
        /// </summary>
        internal static string CollectionChangedItemCountUnexpected {
            get {
                return ResourceManager.GetString("CollectionChangedItemCountUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected item does not equal the actual item provided in the NotifyCollectionChangedEventArgs.{0} property..
        /// </summary>
        internal static string CollectionChangedItemUnexpected {
            get {
                return ResourceManager.GetString("CollectionChangedItemUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CollectionChanged event was raised more than once..
        /// </summary>
        internal static string CollectionChangedMoreThanOnce {
            get {
                return ResourceManager.GetString("CollectionChangedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected new starting index was {0}, but the actual new starting index is {1}..
        /// </summary>
        internal static string CollectionChangedNewIndexNotExpected {
            get {
                return ResourceManager.GetString("CollectionChangedNewIndexNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CollectionChanged event was not raised..
        /// </summary>
        internal static string CollectionChangedNotRaised {
            get {
                return ResourceManager.GetString("CollectionChangedNotRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotifyCollectionChangedEventArgs.{0} property was not expected to be null..
        /// </summary>
        internal static string CollectionChangedNullItems {
            get {
                return ResourceManager.GetString("CollectionChangedNullItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected old starting index was {0}, but the actual old starting index is {1}..
        /// </summary>
        internal static string CollectionChangedOldIndexNotExpected {
            get {
                return ResourceManager.GetString("CollectionChangedOldIndexNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotifyCollectionChangedEventArgs.{0} property was expected to be empty or null..
        /// </summary>
        internal static string CollectionChangedWithItems {
            get {
                return ResourceManager.GetString("CollectionChangedWithItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected collection count was {0}, but that actual count is {1}..
        /// </summary>
        internal static string CollectionCountUnexpected {
            get {
                return ResourceManager.GetString("CollectionCountUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified item was not removed from the collection..
        /// </summary>
        internal static string CollectionItemNotRemoved {
            get {
                return ResourceManager.GetString("CollectionItemNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was expected, but not thrown..
        /// </summary>
        internal static string ExceptionNotThrown {
            get {
                return ResourceManager.GetString("ExceptionNotThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type {0} was expected, but not thrown..
        /// </summary>
        internal static string ExceptionOfTNotThrown {
            get {
                return ResourceManager.GetString("ExceptionOfTNotThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; must refer to a property declared by type {1}..
        /// </summary>
        internal static string ExpressionMustReferToPropertyOfDeclaredType {
            get {
                return ResourceManager.GetString("ExpressionMustReferToPropertyOfDeclaredType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; must refer to a property..
        /// </summary>
        internal static string ExpresssionMustReferToProperty {
            get {
                return ResourceManager.GetString("ExpresssionMustReferToProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is invalid. The value cannot be null..
        /// </summary>
        internal static string NullParameterToAssert {
            get {
                return ResourceManager.GetString("NullParameterToAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PropertyChanged event was not raised for property &apos;{0}&apos;..
        /// </summary>
        internal static string PropertyChangedNotRaised {
            get {
                return ResourceManager.GetString("PropertyChangedNotRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PropertyChanged event was not raised for the following properties: {0}..
        /// </summary>
        internal static string PropertyChangedNotRaisedForExpectedProperties {
            get {
                return ResourceManager.GetString("PropertyChangedNotRaisedForExpectedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PropertyChanged event was raised for property &apos;{0}&apos;..
        /// </summary>
        internal static string PropertyChangedRaised {
            get {
                return ResourceManager.GetString("PropertyChangedRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PropertyChanged event was raised, but not expected for the following properties: {0}..
        /// </summary>
        internal static string PropertyChangedRaisedForUnexpectedProperties {
            get {
                return ResourceManager.GetString("PropertyChangedRaisedForUnexpectedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence contains the element &apos;{0}&apos;..
        /// </summary>
        internal static string SequenceContains {
            get {
                return ResourceManager.GetString("SequenceContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence does not contain the element &apos;{0}&apos;..
        /// </summary>
        internal static string SequenceDoesNotContain {
            get {
                return ResourceManager.GetString("SequenceDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual sequence is not a subset of the expected superset sequence..
        /// </summary>
        internal static string SequenceIsNotSubsetOf {
            get {
                return ResourceManager.GetString("SequenceIsNotSubsetOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual sequence is a subset of the expected superset sequence..
        /// </summary>
        internal static string SequenceIsSubsetOf {
            get {
                return ResourceManager.GetString("SequenceIsSubsetOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual sequence is the same as the expected sequence..
        /// </summary>
        internal static string SequencesAreEqual {
            get {
                return ResourceManager.GetString("SequencesAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual sequence is equivalent to the expected sequence..
        /// </summary>
        internal static string SequencesAreEquivalent {
            get {
                return ResourceManager.GetString("SequencesAreEquivalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual sequence is not the same as the expected sequence..
        /// </summary>
        internal static string SequencesAreNotEqual {
            get {
                return ResourceManager.GetString("SequencesAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual sequence is not equivalent to the expected sequence..
        /// </summary>
        internal static string SequencesAreNotEquivalent {
            get {
                return ResourceManager.GetString("SequencesAreNotEquivalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence contains one or more null elements..
        /// </summary>
        internal static string SomeItemsAreNull {
            get {
                return ResourceManager.GetString("SomeItemsAreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected exception was {0}, but an exception of type {1} was thrown..
        /// </summary>
        internal static string WrongException {
            get {
                return ResourceManager.GetString("WrongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The excepted parameter associated with the exception was &apos;{0}&apos;, but &apos;{1}&apos; was supplied..
        /// </summary>
        internal static string WrongParameterName {
            get {
                return ResourceManager.GetString("WrongParameterName", resourceCulture);
            }
        }
    }
}
